/*import { Inter } from "next/font/google";
import "./globals.css";
import { Bangers, Quicksand, Roboto_Condensed } from 'next/font/google'

import Nav from './components/Nav'
import Nav2 from './components/NavBar'
import Footer from "./components/Footer"
import CartMobileIcon from "./components/CartMobileIcon"
// provider
import CartProvider from "./context/CartContext"
// components
import CartMobile from "./components/CartMobile"
import CartDesktop from "./components/CartDesktop"
import PizzaCategories from "./components/PizzaCategories";

import AuthProvider from '@/providers/authProvider';
const quicksand = Quicksand({
  subsets: ['latin'],
  variable: '--font-quicksand'
})

const bangers = Bangers({
  subsets: ['latin'],
  variable: '--font-bangers',
  weight: ['400']
})

const robotoCondensed = Roboto_Condensed({
  subsets: ['latin'],
  variable: '--font-robotoCondensed',
  weight: ['300', '400', '700']
})

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <CartProvider>
      <AuthProvider>
        
    <html lang="en">
      <body  className={`
      ${inter.className}
      ${quicksand.variable}
      ${bangers.variable}
      ${robotoCondensed.variable} font-quicksand
      `}
      >
        
        <Nav />
      <CartMobileIcon />
      <CartMobile />
      {children}
      <CartDesktop />
      <PizzaCategories />
      <Footer /> 
      
      </body>
      
    </html>
    </AuthProvider>
    </CartProvider>
  );
}*/
import { Inter } from "next/font/google";
import "./globals.css";
import { Bangers, Quicksand, Roboto_Condensed } from 'next/font/google'

import Nav from './components/Nav'
import Nav2 from './components/NavBar'
import Footer from "./components/Footer"
import CartMobileIcon from "./components/CartMobileIcon"
// provider
import CartProvider from "./context/CartContext"
// components
import CartMobile from "./components/CartMobile"
import CartDesktop from "./components/CartDesktop"
import PizzaCategories from "./components/PizzaCategories";

import AuthProvider from '@/providers/authProvider';
const quicksand = Quicksand({
  subsets: ['latin'],
  variable: '--font-quicksand'
})

const bangers = Bangers({
  subsets: ['latin'],
  variable: '--font-bangers',
  weight: ['400']
})

const robotoCondensed = Roboto_Condensed({
  subsets: ['latin'],
  variable: '--font-robotoCondensed',
  weight: ['300', '400', '700']
})

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <CartProvider>
      <AuthProvider>
        
    <html lang="en">
      <body  className={`
      ${inter.className}
      ${quicksand.variable}
      ${bangers.variable}
      ${robotoCondensed.variable} font-quicksand
      `}
      >
        
        
      {children}
      
      
      </body>
      
    </html>
    </AuthProvider>
    </CartProvider>
  );
}


